// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_FkfGYKlA2_-fZlF8fNLlA_l67h4hokY',
    appId: '1:356663315944:web:1670996082af56f7abe85d',
    messagingSenderId: '356663315944',
    projectId: 'gallery-7aeaa',
    authDomain: 'gallery-7aeaa.firebaseapp.com',
    storageBucket: 'gallery-7aeaa.appspot.com',
    measurementId: 'G-9E8XYC66TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevVXlIvi2NWW5TqnDIwnYM6P6vUG-zbk',
    appId: '1:356663315944:android:e54d20e555159362abe85d',
    messagingSenderId: '356663315944',
    projectId: 'gallery-7aeaa',
    storageBucket: 'gallery-7aeaa.appspot.com',
  );
}
